### ISSUE TITLE
; delete  problem

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/mw-dev#13]
For each `<L>` there needs to be a balancing `<LEND>`.

In mw_AB.txt,  this 'balanced' condition is violated.

This problem needs to be fixed.

one example:
```
line 736
<L>213<pc>2,1<k1>akalmaṣa<k2>a-kalmaṣa<e>1
<s>a-kalmaṣa</s>, <lex>mf(<s>{ā}</s>)n.</lex>	¦ spotless.
; delete
; delete
<s>a-kalmaṣa</s>, <lex>m.</lex>	¦ <ab>N.</ab> of the fourth <s1>Manu</s1>, <ls>MatsyaP.</ls> //add(1308,1)
; delete   <<< this should be <LEND>
<L>213.2<pc>1308,1<k1>akalmāṣa<k2>á-kalmāṣa<e>1
```
Another example:
```
line 1646
<L>450<pc>3,1<k1>akṣāgrakīla<k2>akṣāgra-kīla<e>3
<s>akṣ〈ā〉gra-kīla</s> or <s>akṣ〈ā〉gra-kīlaka</s>, <lex>m.</lex>	¦ a linch-pin;
<LEND>    <<<< Should be '; delete'
; delete
	¦ the pin fastening the yoke to the pole.
<LEND>
; delete
; delete
; delete
; delete
; delete
; delete
<L>454<pc>3,1<k1>akṣānah<k2>akṣā-náh<e>3
```

@Andhrabharati   Can you fix this?   There appear to be many  (perhaps a few thousand) such instances.  
If you prefer (such as because of your other family obligations now), and don't mind me changing mw_AB.txt,  I can undertake to do the fix.

**Comment by Andhrabharati** [comment]
> @Andhrabharati Can you fix this?

Yes @funderburkjim , I will correct this error and update the file.

> There appear to be many (perhaps a few thousand) such instances.

There are just about 240 cases to 'handle'--
`missing <LEND> between two <L> lines: 12 cases`
`repeated <LEND> between two <L> lines: 8 cases`
`two <LEND> lines between two <L> lines: 218 cases`

[L and LEND counts tallying.txt](https://github.com/sanskrit-lexicon/mw-dev/files/10715898/L.and.LEND.counts.tallying.txt)
Not that many (!), though even a single occurrence should also be corrected.

**Comment by Andhrabharati** [comment]
Corrected, and @funderburkjim may close the issue after checking the updated file once.

**Comment by funderburkjim** [comment]
AB's corrections satisfy my concerns.
