### ISSUE TITLE
spelling changes during transcoding

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/mw-dev#14]
mw_AB needs to be transcoded to slp1, in order for current display systems to function properly.

During the course of this conversion, a few changes were made (in a temporary copy) of mw_AB.txt.
These changes are shown in [mwtranscode/change_ab_1.txt](https://github.com/sanskrit-lexicon/mw-dev/blob/main/orig/mwtranscode/change_ab_1.txt).

Request @Andhrabharati to make these changes in mw_AB.txt.

**Comment by Andhrabharati** [comment]
While I have changed 8 lines [2667, 230411, 102414, 141321, 815036, 108492, 239075 and 239076] as per the observations by @funderburkjim , I hesitate changing the other 5 lines [`ă change to a` (37436); `ă change to a` (116756); `ŭ́ -> ú` (118589); `ŭ́ -> ú` (369500); `ŭ́ -> ú   <s>°rŭ́</s>` (425594)].

I do understand that the breve accent mark has no equivalent in slp1 or other encodings, it does have a significance (esp. the pronunciation etc.).
https://www.dictionary.com/browse/breve

Also in line 116756 specifically,
"(causing the change of {ā} and **a** to **a** before ṛ)" will have no 'proper sense' as compared to the printed text
"(causing the change of {ā} and **a** to **ă** before ṛ)"

Request Jim to find a suitable solution to retain this breve accent mark and still 'handle' the transliteration to various schemes.
[Probably he could add an 'exception' entry, equating the 'breve'-ed letter ('ă' and 'ŭ') to a plain small-letter ('a' and 'u') internally.]

**Comment by funderburkjim** [comment]
## Use `<s1>` tag.

For those 5 with a breve-accented vowel,
let's change `<s>X</s>` to `<s1>X</s1>`.
This will get avoid the difficulty of displaying such an X in Devanagari, slp1, etc.
See [mwtranscode/change_ab_1a.txt](https://github.com/sanskrit-lexicon/mw-dev/blob/main/orig/mwtranscode/change_ab_1a.txt).

Maybe @Andhrabharati  can make these few changes in mw_AB.txt ?

**Comment by Andhrabharati** [comment]
Yes, this indeed is a simple solution, @funderburkjim !

I will change those 5 lines and push again now.

**Comment by Andhrabharati** [comment]
Luckily these are not at the HW position, so that the 'problem' could be resolved by putting them under s1-tag.

Pushed the latest file, with the 5 lines modified.

**Comment by funderburkjim** [comment]
Nothing else to mention in this issue.  No current problems in transcoding.
