### ISSUE TITLE
ūrdhvajānu two entries needed

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/mw-dev#17]
This one entry of mw_AB.txt is problematic because it has 2 values for k1.
No other entries of mw_AB.txt exhibit this problem.

```
<L>38165.1<pc>1322,3<k1>ūrdhvajānu, ūrdhvajñu<k2>ūrdhva—jānu, ūrdhvá—jñu<e>3
<s>ūrdhva—jānu</s>, <s>ūrdhvajñu</s>	¦ long-shanked, <ls>L.</ls>
<LEND>
```
In cdsl mw, there are two entries:
```
<L>38165.1<pc>1322,3<k1>UrDvajAnu<k2>UrDva—jAnu<e>3A
¦ long-shanked, <ls>L.</ls><info or="38165.1,UrDvajAnu;38168.1,UrDvajYu"/><info n="sup"/><info lex="inh"/>
<LEND>
..... 
<L>38168.1<pc>1322,3<k1>UrDvajYu<k2>UrDva—jYu<e>3A
¦ long-shanked, <ls>L.</ls><info or="38165.1,UrDvajAnu;38168.1,UrDvajYu"/><info n="sup"/><info lex="inh"/>
<LEND>
```
The change could be made by re-instating 38168.1 entry at lines134966-8
```

**Comment by Andhrabharati** [comment]
No @funderburkjim 
the change is to remove the second HW at k1, and make it just ūrdhvajānu.

There are about 190 meta-lines having multiple-worded k2 tags; and thousands of "list" entries need to be 'decided' on the formatting, after the duplicated entries having been deleted.

**Comment by funderburkjim** [comment]
Handled in mw_AB by @Andhrabharati.
